<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AIFARBundlePackager</AssemblyName>
    <RootNamespace>AifarBundlePackager.WinForms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AifarBundlePackager.Core\AifarBundlePackager.Core.csproj" />
  </ItemGroup>

</Project>
